In [25]:
import pandas as pd
df = pd.read_csv('C:\\Users\\ARPIT DUBEY\\salaries.csv')
df.head()

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [26]:
df.rename(columns={
    'salary_more_then_100k': 'more_then_100k'
},inplace=True)
df.columns

Index(['company', 'job', 'degree', 'more_then_100k'], dtype='object')

In [27]:
#indepedent variabble 
inputs= df.drop(['more_then_100k'],axis ='columns')
#dependent variable
target = df['more_then_100k']

In [29]:
inputs.head()

  company                  job     degree
0  google      sales executive  bachelors
1  google      sales executive    masters
2  google     business manager  bachelors
3  google     business manager    masters
4  google  computer programmer  bachelors

In [30]:
target.head()

0    0
1    0
2    1
3    1
4    0
Name: more_then_100k, dtype: int64

In [32]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

In [43]:
inputs['company_n'] = le.fit_transform(inputs['company'])
inputs['job_n'] = le.fit_transform(inputs['job'])
inputs['degree_n'] = le.fit_transform(inputs['degree'])

In [46]:
inputs_n = inputs.drop(['company','job','degree'],axis='columns')

In [49]:
inputs_n

    company_n  job_n  degree_n
0           2      2         0
1           2      2         1
2           2      0         0
3           2      0         1
4           2      1         0
5           2      1         1
6           0      2         1
7           0      1         0
8           0      0         0
9           0      0         1
10          1      2         0
11          1      2         1
12          1      0         0
13          1      0         1
14          1      1         0
15          1      1         1

In [55]:
from sklearn import tree

In [56]:
model = tree.DecisionTreeClassifier()

In [58]:
model.fit(inputs_n,target)

DecisionTreeClassifier()

In [59]:
model.score(inputs_n,target)

1.0

In [62]:
model.predict([[2,2,0]])

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)

In [ ]:
#AN EXERCISE

In [66]:
import pandas as pd 
d = pd.read_csv('C:\\Users\\ARPIT DUBEY\\titanic.csv')
d.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [69]:
df = d.drop(['PassengerId','Name','Ticket','SibSp','Parch','Cabin','Embarked'],axis='columns')
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [71]:
#independent variable
inputs = df.drop('Survived',axis='columns')
#dependent variable
target = df['Survived']

In [104]:
target

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [75]:
type(inputs['Sex']) # as this is a string & the model cant take string as an input , we need a numeric only input !!

pandas.core.series.Series

In [92]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

In [94]:
inputs.head()

   Pclass  Sex   Age     Fare
0       3    0  22.0   7.2500
1       1    1  38.0  71.2833
2       3    1  26.0   7.9250
3       1    1  35.0  53.1000
4       3    0  35.0   8.0500

In [95]:
from sklearn.model_selection import train_test_split

In [97]:
X_train, X_test, y_train, y_test = train_test_split(inputs,target)

In [98]:
from sklearn import tree

In [99]:
model = tree.DecisionTreeClassifier()

In [100]:
model.fit(X_train,y_train)

DecisionTreeClassifier()

In [101]:
model.score(X_test,y_test)

0.7713004484304933

In [103]:
model.predict([[1,1,35,53.1]])

C:\Users\ARPIT DUBEY\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)

In [105]:
# DONE